FROM debian:bookworm-slim@sha256:60eac759739651111db372c07be67863818726f754804b8707c90979bda511df

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       calculix-ccx=2.20-1 \
       python3 python3-numpy python3-scipy python3-matplotlib python3-sklearn ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /solver
COPY calculix ./calculix
ENTRYPOINT ["bash", "/solver/calculix/run-calculix.sh"]
