"""Train and export a deep XY regressor as 64-unit Solist-AI stages.

The ML63Q25x7 Solist driver supports ReLU and externally supplied alpha
weights, but limits one invocation to 64 hidden units.  A wider MLP can still
be executed by partitioning every hidden layer into 64-unit banks and running
the banks sequentially.  Intermediate activations are bfloat16, exactly as on
the accelerator boundary.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any
import warnings

import numpy as np
from sklearn.exceptions import ConvergenceWarning
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

from .dummy_model_pipeline import quantize_bfloat16, to_bfloat16_bits
from .pc_position_runtime import extract_live_features
from .pc_xy_regression import parameter_count
from .sampling_experiment import (
    DEFAULT_SESSION_IDS,
    PANEL_HEIGHT_MM,
    PANEL_WIDTH_MM,
    load_experiment_dataset,
    make_loso_folds,
    regression_metrics,
)


BANK_WIDTH = 64
INPUT_COUNT = 128
OUTPUT_COUNT = 2
SEED = 1
# A uniform shape lets the vendor binary register one Solist instance once,
# then replace alpha between passes.  Greater depth recovers the capacity
# lost by constraining every hidden layer to the hardware's 64-unit limit.
STAGED_HIDDEN = (64, 64, 64, 64, 64, 64, 64)
FIXED_ENGINE_INPUT = INPUT_COUNT + 1


def _staged_model(seed: int) -> MLPRegressor:
    return MLPRegressor(
        hidden_layer_sizes=STAGED_HIDDEN,
        activation="relu",
        solver="adam",
        alpha=1e-3,
        batch_size=64,
        learning_rate_init=5e-4,
        max_iter=700,
        early_stopping=True,
        validation_fraction=0.15,
        n_iter_no_change=40,
        random_state=seed,
    )


def staged_bfloat16_predict(model: Any, standardized: np.ndarray) -> np.ndarray:
    """Emulate sequential Solist passes with bfloat16 at every boundary."""
    values = quantize_bfloat16(np.asarray(standardized, dtype=np.float32))
    for weights, bias in zip(model.coefs_[:-1], model.intercepts_[:-1]):
        weights_q = quantize_bfloat16(weights)
        bias_q = quantize_bfloat16(bias)
        banks = []
        for start in range(0, weights.shape[1], BANK_WIDTH):
            stop = min(start + BANK_WIDTH, weights.shape[1])
            activated = np.maximum(
                values @ weights_q[:, start:stop] + bias_q[start:stop], 0.0
            )
            banks.append(quantize_bfloat16(activated))
        values = np.concatenate(banks, axis=1)
    output = values @ quantize_bfloat16(model.coefs_[-1])
    output += quantize_bfloat16(model.intercepts_[-1])
    return np.clip(quantize_bfloat16(output), 0.0, 1.0)


def solist_stage_layout(model: Any) -> list[dict[str, int | str]]:
    """Describe the accelerator calls needed for one deep prediction."""
    result: list[dict[str, int | str]] = []
    for layer, weights in enumerate(model.coefs_):
        output_size = int(weights.shape[1])
        activation = "relu" if layer < len(model.coefs_) - 1 else "linear"
        for bank, start in enumerate(range(0, output_size, BANK_WIDTH)):
            width = min(BANK_WIDTH, output_size - start)
            result.append({
                "layer": layer,
                "bank": bank,
                "input_size": FIXED_ENGINE_INPUT,
                "hidden_size": BANK_WIDTH,
                "output_size": BANK_WIDTH,
                "active_input_size": int(weights.shape[0] + 1),
                "active_output_size": width,
                "activation": "relu",
            })
    return result


def _c_bfloat_array(name: str, values: np.ndarray, columns: int = 12) -> str:
    bits = to_bfloat16_bits(values).reshape(-1)
    rows = []
    for offset in range(0, len(bits), columns):
        rows.append("    " + ", ".join(
            f"0x{int(value):04X}" for value in bits[offset:offset + columns]
        ) + ",")
    return f"static const int16_t {name}[{len(bits)}] = {{\n" + "\n".join(rows) + "\n};\n"


def _c_float_array(name: str, values: np.ndarray, columns: int = 6) -> str:
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    rows = []
    for offset in range(0, len(flat), columns):
        rows.append("    " + ", ".join(
            f"{float(value):.9g}F" for value in flat[offset:offset + columns]
        ) + ",")
    return f"static const float {name}[{len(flat)}] = {{\n" + "\n".join(rows) + "\n};\n"


def export_header(
    path: Path,
    scaler: StandardScaler,
    model: Any,
    golden_inputs: np.ndarray,
    golden_outputs: np.ndarray,
) -> int:
    """Export pre-partitioned alpha banks; biases use an appended constant input."""
    pieces = [
        "/* Generated by python -m sim.solist_xy_staged. Do not edit. */\n",
        "#ifndef APAN_XY_STAGED_MODEL_H\n#define APAN_XY_STAGED_MODEL_H\n",
        "#include <stdint.h>\n",
        f"#define APAN_XY_INPUT_SIZE {INPUT_COUNT}\n",
        f"#define APAN_XY_OUTPUT_SIZE {OUTPUT_COUNT}\n",
        f"#define APAN_XY_BANK_WIDTH {BANK_WIDTH}\n",
        f"#define APAN_XY_LAYER_COUNT {len(model.coefs_)}\n",
        f"#define APAN_XY_PREDICT_PASS_COUNT {len(solist_stage_layout(model))}\n",
        f"#define APAN_XY_GOLDEN_CASE_COUNT {len(golden_inputs)}\n",
        "#define APAN_XY_ACTIVATION_RELU 2\n",
        "#define APAN_XY_ACTIVATION_LINEAR 0\n",
    ]
    pieces.append(_c_float_array("apan_xy_feature_mean", scaler.mean_))
    pieces.append(_c_float_array("apan_xy_feature_scale", scaler.scale_))
    weight_bytes = 0
    for layer, (weights, bias) in enumerate(zip(model.coefs_, model.intercepts_)):
        output_size = weights.shape[1]
        bank_count = (output_size + BANK_WIDTH - 1) // BANK_WIDTH
        if weights.shape[0] > INPUT_COUNT:
            raise ValueError("fixed Solist engine supports at most 128 active inputs")
        pieces.append(f"#define APAN_XY_LAYER_{layer}_INPUT_SIZE {FIXED_ENGINE_INPUT}\n")
        pieces.append(f"#define APAN_XY_LAYER_{layer}_OUTPUT_SIZE {output_size}\n")
        pieces.append(f"#define APAN_XY_LAYER_{layer}_BANK_COUNT {bank_count}\n")
        for bank, start in enumerate(range(0, output_size, BANK_WIDTH)):
            stop = min(start + BANK_WIDTH, output_size)
            alpha = np.zeros((FIXED_ENGINE_INPUT, BANK_WIDTH), dtype=np.float32)
            alpha[:weights.shape[0], :stop - start] = weights[:, start:stop]
            alpha[-1, :stop - start] = bias[start:stop]
            pieces.append(_c_bfloat_array(f"apan_xy_layer_{layer}_bank_{bank}_alpha", alpha))
            weight_bytes += int(alpha.size * 2)
    identity = np.eye(BANK_WIDTH, dtype=np.float32)
    pieces.append(_c_bfloat_array("apan_xy_identity_beta_64", identity))
    pieces.append(_c_bfloat_array("apan_xy_golden_inputs", golden_inputs))
    pieces.append(_c_float_array("apan_xy_golden_outputs", golden_outputs))
    weight_bytes += int(identity.size * 2)
    pieces.append("#endif\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(pieces), encoding="ascii")
    return weight_bytes


def run(sessions_root: Path, output_dir: Path, header: Path) -> dict[str, Any]:
    dataset = load_experiment_dataset(sessions_root, DEFAULT_SESSION_IDS)
    features = np.stack([
        extract_live_features(waveform[:512]) for waveform in dataset.samples
    ])
    targets = dataset.xy_mm / (PANEL_WIDTH_MM, PANEL_HEIGHT_MM)
    float_prediction = np.empty_like(targets)
    bfloat_prediction = np.empty_like(targets)
    folds: list[dict[str, Any]] = []
    warnings.filterwarnings("ignore", category=ConvergenceWarning)

    for fold, (train_sessions, test_session) in enumerate(
        make_loso_folds(dataset.session_ids), start=1
    ):
        train = np.isin(dataset.session_ids, train_sessions)
        test = dataset.session_ids == test_session
        scaler = StandardScaler().fit(features[train])
        train_x = scaler.transform(features[train])
        test_x = scaler.transform(features[test])
        model = _staged_model(SEED)
        model.fit(train_x, targets[train])
        float_mm = np.clip(model.predict(test_x), 0.0, 1.0) * (
            PANEL_WIDTH_MM, PANEL_HEIGHT_MM
        )
        bfloat_mm = staged_bfloat16_predict(model, test_x) * (
            PANEL_WIDTH_MM, PANEL_HEIGHT_MM
        )
        float_prediction[test] = float_mm / (PANEL_WIDTH_MM, PANEL_HEIGHT_MM)
        bfloat_prediction[test] = bfloat_mm / (PANEL_WIDTH_MM, PANEL_HEIGHT_MM)
        folds.append({
            "fold": fold,
            "test_session": test_session,
            "test_count": int(test.sum()),
            "float": regression_metrics(dataset.xy_mm[test], float_mm),
            "staged_bfloat16": regression_metrics(dataset.xy_mm[test], bfloat_mm),
        })

    float_mm = float_prediction * (PANEL_WIDTH_MM, PANEL_HEIGHT_MM)
    bfloat_mm = bfloat_prediction * (PANEL_WIDTH_MM, PANEL_HEIGHT_MM)
    quantization_delta = np.linalg.norm(float_mm - bfloat_mm, axis=1)

    scaler = StandardScaler().fit(features)
    model = _staged_model(SEED)
    model.fit(scaler.transform(features), targets)
    golden_indices = [int(np.flatnonzero(dataset.labels == label)[0]) for label in range(8)]
    golden_inputs = scaler.transform(features[golden_indices]).astype(np.float32)
    golden_outputs = staged_bfloat16_predict(model, golden_inputs).astype(np.float32)
    output_dir.mkdir(parents=True, exist_ok=True)
    arrays: dict[str, np.ndarray] = {
        "feature_mean": scaler.mean_.astype(np.float32),
        "feature_scale": scaler.scale_.astype(np.float32),
    }
    for layer, (weights, bias) in enumerate(zip(model.coefs_, model.intercepts_)):
        arrays[f"layer_{layer}_weights"] = weights.astype(np.float32)
        arrays[f"layer_{layer}_bias"] = bias.astype(np.float32)
        arrays[f"layer_{layer}_weights_bfloat16"] = to_bfloat16_bits(weights)
        arrays[f"layer_{layer}_bias_bfloat16"] = to_bfloat16_bits(bias)
    np.savez_compressed(output_dir / "solist_xy_staged_model.npz", **arrays)
    np.savez_compressed(
        output_dir / "loso_predictions.npz",
        expected_xy_mm=dataset.xy_mm,
        float_xy_mm=float_mm,
        staged_bfloat16_xy_mm=bfloat_mm,
        session_ids=dataset.session_ids,
    )
    flash_weight_bytes = export_header(
        header, scaler, model, golden_inputs, golden_outputs
    )
    layout = solist_stage_layout(model)
    report = {
        "experiment": "solist_xy_staged_relu_v1",
        "dataset_sha256": dataset.dataset_sha256,
        "sample_count": int(len(dataset.labels)),
        "session_ids": list(DEFAULT_SESSION_IDS),
        "input": "512 samples at 25.6 kHz; time64 + FFT-band64",
        "architecture": [INPUT_COUNT, *STAGED_HIDDEN, OUTPUT_COUNT],
        "trainable_parameters": parameter_count(INPUT_COUNT, STAGED_HIDDEN, OUTPUT_COUNT),
        "seed": SEED,
        "precision": "bfloat16 inputs, weights, hidden-stage outputs, and final output",
        "solist": {
            "max_hidden_per_pass": BANK_WIDTH,
            "predict_pass_count": len(layout),
            "layout": layout,
            "activation": "ReLU for hidden stages; linear for final stage",
            "weight_and_identity_beta_bytes": flash_weight_bytes,
            "requires_external_alpha": True,
            "online_learning": False,
        },
        "float_metrics": regression_metrics(dataset.xy_mm, float_mm),
        "staged_bfloat16_metrics": regression_metrics(dataset.xy_mm, bfloat_mm),
        "quantization_delta_mm": {
            "mean": float(np.mean(quantization_delta)),
            "p90": float(np.percentile(quantization_delta, 90)),
            "max": float(np.max(quantization_delta)),
        },
        "folds": folds,
        "model": str(output_dir / "solist_xy_staged_model.npz"),
        "header": str(header),
        "scope": "eight centre coordinates only; arbitrary-position interpolation is unverified",
    }
    (output_dir / "training_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sessions", type=Path, default=Path("data/raw/sessions"))
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/solist_xy_staged"))
    parser.add_argument(
        "--header", type=Path,
        default=Path("firmware/AcrylicPanCollector/generated/apan_xy_staged_model.h"),
    )
    args = parser.parse_args()
    report = run(args.sessions, args.output_dir, args.header)
    metrics = report["staged_bfloat16_metrics"]
    print(f"Solist staged bfloat16 mean distance={metrics['mean_distance_mm']:.2f} mm")
    print(f"p90={metrics['p90_distance_mm']:.2f} mm; passes={report['solist']['predict_pass_count']}")


if __name__ == "__main__":
    main()
